dist: xenial
language: python
python:
  - 3.7

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install codecov

install:
  - pip install ".[test]" .

script: 
  - export PYTHONPATH=`pwd`
  - pytest --cov=mlir --cov-report=xml --cov-report=term

after_success:
  - codecov
